version: '3.1'

services:

  api:
    build: .
    command: node_modules/.bin/nodemon --legacy-watch -w app.js -w api/ -w config/ app.js
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 8080:8080
    environment:
      - NODE_ENV=development
      - PORT=8080
      - SUPPRESS_NO_CONFIG_WARNING=true
    links:
      - mongo
      - redis
    depends_on:
      - mongo
      - redis

  redis:
    image: redis
    restart: always

  # https://docs.docker.com/samples/library/mongo/#-via-docker-stack-deploy-or-docker-compose
  mongo:
    image: mongo
    restart: always

  # Helpful web UI for mongo development
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
